In [10]:
import sys
from dotenv import load_dotenv

sys.path.insert(0, '.')
load_dotenv(override=True)

from src.data.macro import (
    fetch_treasury_rates,
    fetch_gdp_growth,
    fetch_fed_funds,
    fetch_unemployment,
    fetch_cpi,
    fetch_hy_oas,
)
print('imports ok')

imports ok

In [11]:
try:
    df = fetch_treasury_rates()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(6522, 3)  range=2000-01-03 -> 2024-12-31

            treasury_3m  treasury_10y  term_spread
date
2000-01-03         5.48          6.58         1.10
2000-01-04         5.43          6.49         1.06
2000-01-05         5.44          6.62         1.18

In [12]:
try:
    df = fetch_gdp_growth()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(100, 1)  range=2000-01-01 -> 2024-10-01

            gdp_growth_qoq
date
2000-01-01             1.5
2000-04-01             7.5
2000-07-01             0.4

In [13]:
try:
    df = fetch_fed_funds()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(300, 1)  range=2000-01-01 -> 2024-12-01

            fed_funds_rate
date
2000-01-01            5.45
2000-02-01            5.73
2000-03-01            5.85

In [14]:
try:
    df = fetch_unemployment()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(300, 2)  range=2000-01-01 -> 2024-12-01

            unemployment_rate  unemployment_change
date
2000-01-01                4.0                  NaN
2000-02-01                4.1                  0.1
2000-03-01                4.0                 -0.1

In [15]:
try:
    df = fetch_cpi()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(300, 2)  range=2000-01-01 -> 2024-12-01

              cpi  cpi_yoy
date
2000-01-01  169.3      NaN
2000-02-01  170.0      NaN
2000-03-01  171.0      NaN

In [16]:
try:
    df = fetch_hy_oas()
    print(f"PASS  shape={df.shape}  range={df.index.min().date()} -> {df.index.max().date()}")
    display(df.head(3))
except Exception as e:
    print(f"FAIL  {e}")

PASS  shape=(414, 1)  range=2023-06-09 -> 2024-12-31

            hy_oas
date
2023-06-09    4.29
2023-06-12    4.34
2023-06-13    4.18